import UIKit

/// Family reports and printables, drawn natively. Mirrors the web's
/// `lib/utils/export.ts` (same four documents, same CSV columns, same file
/// names) so a family gets the same answer from either app. Unlike jsPDF's
/// built-in fonts, UIKit shapes every script, so riyal signs and Arabic
/// names print as typed.
enum FamilyExport {

    enum TemplateStyle: String, CaseIterable, Identifiable {
        case stars, rainbow, minimal

        var id: String { rawValue }

        var label: String {
            switch self {
            case .stars: return String(localized: "Stars")
            case .rainbow: return String(localized: "Rainbow")
            case .minimal: return String(localized: "Minimal")
            }
        }

        /// Same RGB triples as the web templates.
        fileprivate var primary: UIColor {
            switch self {
            case .stars: return rgb(99, 102, 241)
            case .rainbow: return rgb(236, 72, 153)
            case .minimal: return rgb(31, 41, 55)
            }
        }

        fileprivate var background: UIColor {
            switch self {
            case .stars: return rgb(238, 242, 255)
            case .rainbow: return rgb(255, 241, 242)
            case .minimal: return rgb(249, 250, 251)
            }
        }

        fileprivate func title(for name: String) -> String {
            switch self {
            case .stars: return String(localized: "\(name)'s Weekly Chore Chart")
            case .rainbow: return String(localized: "\(name)'s Week")
            case .minimal: return String(localized: "\(name): Weekly Chores")
            }
        }

        fileprivate var footer: String {
            switch self {
            case .stars: return String(localized: "You're a star! Keep it up!")
            case .rainbow: return String(localized: "Every chore completed is a step toward something awesome!")
            case .minimal: return String(localized: "Generated by ChoreStar")
            }
        }
    }

    /// One child's week, with the numbers already worked out the way the
    /// dashboard works them out (vacation days skipped, bonus on a perfect week).
    struct ChildWeek {
        let child: Child
        let chores: [Chore]
        let completed: Set<ChoreDayCell>
        let perfectDays: Int
        let dueDays: Int
        let earnedCents: Int
    }

    struct Snapshot {
        let weekStart: String
        let weekStartDate: Date
        let currency: FamilyCurrency
        let children: [ChildWeek]

        var choreCount: Int { children.reduce(0) { $0 + $1.chores.count } }
        var completionCount: Int { children.reduce(0) { $0 + $1.completed.count } }
    }

    // MARK: - Money

    static func cents(_ chore: Chore) -> Int {
        Int((chore.reward * 100).rounded())
    }

    static func money(_ cents: Int, _ currency: FamilyCurrency) -> String {
        let amount = Double(cents) / 100
        if currency.decimals == 0 {
            return currency.symbol + String(format: "%.0f", amount.rounded())
        }
        return currency.symbol + String(format: "%.\(currency.decimals)f", amount)
    }

    // MARK: - CSV

    /// Column headers and day names stay English, matching the web export, so
    /// spreadsheets from either app line up.
    static func csv(_ snapshot: Snapshot) -> String {
        let dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .short
        dateFormatter.timeStyle = .none

        var rows = [["Child Name", "Chore Name", "Completed Date", "Earnings", "Day of Week"]]
        for week in snapshot.children {
            let order = Dictionary(uniqueKeysWithValues: week.chores.map { ($0.id, $0.sortOrder) })
            let cells = week.completed.sorted {
                ($0.dayOfWeek, order[$0.choreId] ?? 0) < ($1.dayOfWeek, order[$1.choreId] ?? 0)
            }
            for cell in cells {
                guard let chore = week.chores.first(where: { $0.id == cell.choreId }) else { continue }
                let date = RewardMath.date(weekStart: snapshot.weekStart, dayIndex: cell.dayOfWeek)
                rows.append([
                    week.child.name,
                    chore.name,
                    date.map(dateFormatter.string(from:)) ?? "",
                    money(cents(chore), snapshot.currency),
                    dayNames[cell.dayOfWeek]
                ])
            }
        }
        // The byte-order mark makes Excel read the file as UTF-8.
        return "\u{FEFF}" + rows
            .map { $0.map { "\"" + $0.replacingOccurrences(of: "\"", with: "\"\"") + "\"" }.joined(separator: ",") }
            .joined(separator: "\n")
    }

    // MARK: - Family report

    static func familyReportPDF(_ snapshot: Snapshot) -> Data {
        let size = portrait
        let margin: CGFloat = 56
        let width = size.width - margin * 2
        let percent = NumberFormatter()
        percent.numberStyle = .percent

        return renderer(size: size, title: String(localized: "ChoreStar Family Report")).pdfData { context in
            context.beginPage()
            var y = margin
            func ensureRoom(_ height: CGFloat) {
                if y + height > size.height - margin {
                    context.beginPage()
                    y = margin
                }
            }
            func line(_ text: String, size: CGFloat = 11, weight: UIFont.Weight = .regular,
                      color: UIColor = .black, indent: CGFloat = 0, after: CGFloat) {
                ensureRoom(after)
                draw(text, in: CGRect(x: margin + indent, y: y, width: width - indent, height: size * 1.5),
                     size: size, weight: weight, color: color)
                y += after
            }

            line(String(localized: "ChoreStar Family Report"), size: 22, weight: .bold, after: 32)
            line(String(localized: "Generated on \(dateString(Date(), style: .medium))"), color: .darkGray, after: 16)
            line(String(localized: "Week of \(dateString(snapshot.weekStartDate, style: .medium))"), color: .darkGray, after: 32)

            line(String(localized: "Family Overview"), size: 16, weight: .bold, after: 24)
            line(String(localized: "Total Children: \(snapshot.children.count)"), after: 16)
            line(String(localized: "Total Chores: \(snapshot.choreCount)"), after: 16)
            line(String(localized: "Total Completions: \(snapshot.completionCount)"), after: 32)

            for week in snapshot.children {
                ensureRoom(100)
                let header = week.child.age > 0
                    ? String(localized: "\(week.child.name) (Age \(week.child.age))")
                    : week.child.name
                line(header, size: 14, weight: .semibold, after: 22)
                let rate = week.dueDays > 0 ? Double(week.perfectDays) / Double(week.dueDays) : 0
                line(String(localized: "Completion Rate: \(percent.string(from: NSNumber(value: rate)) ?? "0%")"), after: 16)
                line(String(localized: "Perfect Days: \(week.perfectDays) of \(week.dueDays)"), after: 16)
                line(String(localized: "Total Completions: \(week.completed.count)"), after: 16)
                line(String(localized: "Total Earnings: \(money(week.earnedCents, snapshot.currency))"), after: 22)

                if !week.chores.isEmpty {
                    line(String(localized: "Chore Breakdown:"), weight: .semibold, after: 16)
                    for chore in week.chores {
                        let done = week.completed.filter { $0.choreId == chore.id }.count
                        let each = money(cents(chore), snapshot.currency)
                        line("• " + String(localized: "\(chore.name): \(done) done, \(each) each"),
                             indent: 14, after: 15)
                    }
                }
                y += 20
            }

            draw(String(localized: "Generated by ChoreStar • chorestar.app"),
                 in: CGRect(x: margin, y: size.height - 40, width: width, height: 14),
                 size: 9, color: .gray, alignment: .center)
        }
    }

    // MARK: - Printable chore chart

    /// A landscape tick-sheet for the fridge: every child, every chore, a box
    /// on each day it's due and a grey square where it isn't.
    static func choreChartPDF(_ snapshot: Snapshot) -> Data {
        let size = CGSize(width: portrait.height, height: portrait.width)
        let margin: CGFloat = 40
        let width = size.width - margin * 2
        let nameWidth = width * 0.3
        let columnWidth = (width - nameWidth) / 7
        let rowHeight: CGFloat = 22
        let days = ChoreSchedule.displayOrder()
        let dayNames = Calendar.current.shortWeekdaySymbols

        return renderer(size: size, title: String(localized: "Printable Chore Chart")).pdfData { context in
            var y: CGFloat = 0

            func headerRow() {
                fill(CGRect(x: margin, y: y, width: width, height: rowHeight), rgb(238, 242, 255))
                draw(String(localized: "Child / Chore"), in: CGRect(x: margin + 6, y: y + 5, width: nameWidth - 12, height: 14),
                     size: 10, weight: .bold)
                for (column, day) in days.enumerated() {
                    draw(dayNames[day], in: CGRect(x: margin + nameWidth + CGFloat(column) * columnWidth, y: y + 5,
                                                   width: columnWidth, height: 14),
                         size: 10, weight: .bold, alignment: .center)
                }
                y += rowHeight + 4
            }
            func newPage() {
                context.beginPage()
                y = margin
                draw(String(localized: "ChoreStar Weekly Chore Chart"), in: CGRect(x: margin, y: y, width: width, height: 28),
                     size: 20, weight: .bold)
                y += 28
                draw(String(localized: "Week of \(dateString(snapshot.weekStartDate, style: .medium))"),
                     in: CGRect(x: margin, y: y, width: width, height: 16), size: 11, color: .darkGray)
                y += 26
                headerRow()
            }
            func ensureRoom(_ height: CGFloat) {
                if y + height > size.height - margin - 20 { newPage() }
            }

            newPage()
            for week in snapshot.children {
                ensureRoom(rowHeight * 2)
                draw(week.child.name, in: CGRect(x: margin, y: y + 4, width: width, height: 16), size: 12, weight: .bold)
                y += rowHeight

                if week.chores.isEmpty {
                    draw(String(localized: "(no chores)"), in: CGRect(x: margin + 12, y: y + 4, width: nameWidth, height: 14),
                         size: 10, color: .gray)
                    y += rowHeight
                }
                for chore in week.chores {
                    ensureRoom(rowHeight)
                    draw(chore.name, in: CGRect(x: margin + 12, y: y + 4, width: nameWidth - 18, height: 14), size: 10)
                    for (column, day) in days.enumerated() {
                        let box = CGRect(x: margin + nameWidth + CGFloat(column) * columnWidth + (columnWidth - 12) / 2,
                                         y: y + 4, width: 12, height: 12)
                        if chore.isDue(on: day) {
                            stroke(box, .darkGray, radius: 2)
                        } else {
                            fill(box, rgb(229, 231, 235), radius: 2)
                        }
                    }
                    y += rowHeight
                }
                y += 8
            }

            draw(String(localized: "Generated by ChoreStar • Check off boxes as chores are completed"),
                 in: CGRect(x: margin, y: size.height - 30, width: width, height: 14),
                 size: 9, color: .gray, alignment: .center)
        }
    }

    // MARK: - Weekly templates

    /// One styled page per child (more if the chore list runs long).
    static func weeklyTemplatePDF(_ snapshot: Snapshot, style: TemplateStyle) -> Data {
        let size = portrait
        let margin: CGFloat = 40
        let width = size.width - margin * 2
        let nameWidth = width * 0.3
        let columnWidth = (width - nameWidth) / 7
        let rowHeight: CGFloat = 34
        let days = ChoreSchedule.displayOrder()
        let dayNames = Calendar.current.shortWeekdaySymbols
        let weekOf = String(localized: "Week of \(dateString(snapshot.weekStartDate, style: .long))")

        return renderer(size: size, title: String(localized: "Weekly Template")).pdfData { context in
            for week in snapshot.children {
                var y: CGFloat = 0

                func pageTop() {
                    context.beginPage()
                    fill(CGRect(x: 0, y: 0, width: size.width, height: 110), style.primary)
                    draw(style.title(for: week.child.name), in: CGRect(x: margin, y: 36, width: width, height: 32),
                         size: 24, weight: .bold, color: .white)
                    draw(weekOf, in: CGRect(x: margin, y: 72, width: width, height: 18), size: 12, color: .white)
                    y = 136
                    fill(CGRect(x: margin, y: y, width: width, height: 26), style.background)
                    draw(String(localized: "Chore"), in: CGRect(x: margin + 8, y: y + 6, width: nameWidth - 16, height: 16),
                         size: 11, weight: .bold, color: style.primary)
                    for (column, day) in days.enumerated() {
                        draw(dayNames[day], in: CGRect(x: margin + nameWidth + CGFloat(column) * columnWidth, y: y + 6,
                                                       width: columnWidth, height: 16),
                             size: 11, weight: .bold, color: style.primary, alignment: .center)
                    }
                    y += 30
                }

                pageTop()
                if week.chores.isEmpty {
                    draw(String(localized: "No chores yet. Add some in ChoreStar!"),
                         in: CGRect(x: margin, y: y + 10, width: width, height: 16), size: 11, color: .gray)
                    y += 40
                }
                for (index, chore) in week.chores.enumerated() {
                    if y + rowHeight > size.height - 170 { pageTop() }
                    if index.isMultiple(of: 2) {
                        fill(CGRect(x: margin, y: y, width: width, height: rowHeight), rgb(250, 250, 250))
                    }
                    fill(CGRect(x: margin, y: y + rowHeight - 0.5, width: width, height: 0.5), rgb(229, 231, 235))
                    draw(chore.name, in: CGRect(x: margin + 8, y: y + 5, width: nameWidth - 16, height: 16), size: 11)
                    if chore.reward > 0 {
                        draw(money(cents(chore), snapshot.currency),
                             in: CGRect(x: margin + 8, y: y + 20, width: nameWidth - 16, height: 11), size: 8, color: .gray)
                    }
                    for (column, day) in days.enumerated() {
                        let centerX = margin + nameWidth + CGFloat(column) * columnWidth + columnWidth / 2
                        let box = CGRect(x: centerX - 8, y: y + (rowHeight - 16) / 2, width: 16, height: 16)
                        if chore.isDue(on: day) {
                            stroke(box, style.primary, radius: 4)
                            if style == .stars {
                                draw("★", in: box.insetBy(dx: 0, dy: 2), size: 9, color: rgb(224, 224, 240), alignment: .center)
                            }
                        } else {
                            draw("–", in: box.insetBy(dx: 0, dy: 1), size: 11, color: .lightGray, alignment: .center)
                        }
                    }
                    y += rowHeight
                }

                let scheduled = week.chores.reduce(0) { $0 + cents($1) * ChoreSchedule.normalized($1.daysOfWeek).count }
                let everyDay = week.chores.allSatisfy { ChoreSchedule.normalized($0.daysOfWeek).count == 7 }
                let goal = everyDay
                    ? String(localized: "Weekly Goal: Complete all \(week.chores.count) chores every day")
                    : String(localized: "Weekly Goal: Complete every chore on its scheduled days")
                let summary = CGRect(x: margin, y: max(y + 24, size.height - 150), width: width, height: 60)
                fill(summary, style.background, radius: 8)
                draw(goal, in: CGRect(x: summary.minX + 14, y: summary.minY + 12, width: width - 28, height: 16),
                     size: 12, weight: .bold, color: style.primary)
                if scheduled > 0 {
                    draw(String(localized: "Possible earnings: \(money(scheduled, snapshot.currency)) per week"),
                         in: CGRect(x: summary.minX + 14, y: summary.minY + 34, width: width - 28, height: 14),
                         size: 10, color: .darkGray)
                }

                draw(style.footer, in: CGRect(x: margin, y: size.height - 40, width: width * 0.7, height: 14),
                     size: 9, color: .gray)
                draw("chorestar.app", in: CGRect(x: margin + width * 0.7, y: size.height - 40, width: width * 0.3, height: 14),
                     size: 9, color: .gray, alignment: .right)
            }
        }
    }

    // MARK: - Files

    /// Same names the web uses: `chorestar-family-2026-09-24.pdf`,
    /// `chorestar-chart-family-2026-09-20.pdf`, `chorestar-stars-family-2026-09-20.pdf`.
    static func fileName(_ kind: String, date: String, ext: String) -> String {
        "chorestar-\(kind)-\(date).\(ext)"
    }

    static func write(_ data: Data, named name: String) throws -> URL {
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(name)
        try data.write(to: url, options: .atomic)
        return url
    }

    static var todayString: String {
        VacationMode.string(from: Date(), calendar: .current)
    }

    // MARK: - Drawing

    /// US-style letter paper where people buy it, A4 everywhere else.
    private static var portrait: CGSize {
        let letterRegions: Set<String> = ["US", "CA", "MX", "PH", "CL", "CO", "VE"]
        return letterRegions.contains(Locale.current.region?.identifier ?? "")
            ? CGSize(width: 612, height: 792)
            : CGSize(width: 595.28, height: 841.89)
    }

    private static func renderer(size: CGSize, title: String) -> UIGraphicsPDFRenderer {
        let format = UIGraphicsPDFRendererFormat()
        format.documentInfo = [
            kCGPDFContextTitle as String: title,
            kCGPDFContextCreator as String: "ChoreStar"
        ]
        return UIGraphicsPDFRenderer(bounds: CGRect(origin: .zero, size: size), format: format)
    }

    private static func draw(_ text: String, in rect: CGRect, size: CGFloat, weight: UIFont.Weight = .regular,
                             color: UIColor = .black, alignment: NSTextAlignment = .natural) {
        let paragraph = NSMutableParagraphStyle()
        paragraph.alignment = alignment
        paragraph.lineBreakMode = .byTruncatingTail
        let attributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: size, weight: weight),
            .foregroundColor: color,
            .paragraphStyle: paragraph
        ]
        (text as NSString).draw(with: rect, options: [.usesLineFragmentOrigin, .truncatesLastVisibleLine],
                                attributes: attributes, context: nil)
    }

    private static func fill(_ rect: CGRect, _ color: UIColor, radius: CGFloat = 0) {
        color.setFill()
        UIBezierPath(roundedRect: rect, cornerRadius: radius).fill()
    }

    private static func stroke(_ rect: CGRect, _ color: UIColor, radius: CGFloat = 0) {
        color.setStroke()
        let path = UIBezierPath(roundedRect: rect, cornerRadius: radius)
        path.lineWidth = 1
        path.stroke()
    }

    private static func dateString(_ date: Date, style: DateFormatter.Style) -> String {
        let formatter = DateFormatter()
        formatter.dateStyle = style
        formatter.timeStyle = .none
        return formatter.string(from: date)
    }
}

private func rgb(_ red: CGFloat, _ green: CGFloat, _ blue: CGFloat) -> UIColor {
    UIColor(red: red / 255, green: green / 255, blue: blue / 255, alpha: 1)
}

extension SupabaseManager {
    /// The week the export covers, built from the same data and rules as the
    /// dashboard's week view.
    func exportSnapshot(weekStart: String = RewardMath.weekStartString()) -> FamilyExport.Snapshot {
        let bonusCents = familySettings?.weeklyBonusCents ?? 0
        let weeks = children.map { child -> FamilyExport.ChildWeek in
            let childChores = chores.filter { $0.childId == child.id }.sorted { $0.sortOrder < $1.sortOrder }
            let stats = weekStats(for: child.id, weekStart: weekStart)
            let dueDays = (0..<7).filter { !dueChores(for: child.id, on: $0, weekStart: weekStart).isEmpty }.count
            var earned = stats.dayEarningsCents.reduce(0, +)
            if dueDays > 0 && stats.perfectDayCount == dueDays { earned += bonusCents }
            return FamilyExport.ChildWeek(
                child: child,
                chores: childChores,
                completed: completedCells(for: child.id, weekStart: weekStart),
                perfectDays: stats.perfectDayCount,
                dueDays: dueDays,
                earnedCents: earned
            )
        }
        return FamilyExport.Snapshot(
            weekStart: weekStart,
            weekStartDate: RewardMath.date(weekStart: weekStart, dayIndex: 0) ?? Date(),
            currency: FamilyCurrency.find(familySettings?.currencyCode),
            children: weeks
        )
    }
}
