[build]
  publish = "frontend"
  command = ""

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://unpkg.com https://*.supabase.co; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self' https://*.supabase.co;"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  SUPABASE_URL = "your-production-supabase-url"
  SUPABASE_ANON_KEY = "your-production-supabase-anon-key"

[context.deploy-preview.environment]
  SUPABASE_URL = "your-staging-supabase-url"
  SUPABASE_ANON_KEY = "your-staging-supabase-anon-key" 